### ISSUE TITLE
Не рабочий файл 3ей главы

### ISSUE THREAD

**Issue by Nariusss** [qwqwerertyty/honkai-vns-ru#1]
При попытке прочитать главу, возникает проблема, что файл с переводом сломан, тк первые 2 главы работают спокойно и 4-остальные главы нормально отображаются на английском.

![изображение](https://user-images.githubusercontent.com/42680756/156891233-85f0e9a8-d959-44f8-b5ff-62c4589873e5.png)
![изображение](https://user-images.githubusercontent.com/42680756/156891241-af85e1f9-f4d8-4477-8ad9-a84f47b6593d.png)

**Comment by Nariusss** [comment]
UPD: Ошибка найдена в строке 311. Вы зачем то заменили speak на text
![image](https://user-images.githubusercontent.com/42680756/157497709-d7988cec-1765-42d8-9549-d0751e8f5368.png)

**Comment by qwqwerertyty** [comment]
Понял, спасибо за поправку. Уже выложил исправленный файл. Извиняюсь за задержку. Если найдутся ещё проблемы, буду благодарен за помощь.9 мар. 2022 г. 20:31 пользователь Narius ***@***.***> написал:

UPD: Ошибка найдена в строке 311. Вы зачем то заменили speak на text

**Comment by Nariusss** [comment]
Всегда пожалуйста!
